name: generate docs

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install docdash and jsdoc
      run: npm install docdash jsdoc

    - name: Build
      run: npm run generate-docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        # https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-create-ssh-deploy-key
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs
